import { plainToInstance } from 'class-transformer';
import { PeruseCreateLoadJobResult, PeruseLoadResponse } from '../data';

export const buildStubPeruseCreateLoadJobResult = (
  data?: Partial<PeruseCreateLoadJobResult>,
): PeruseCreateLoadJobResult => {
  const plain = {
    job_id: '66d86482-2416-4c7b-98b6-b58ded700347',
    job_type: 'verifyLoad',
    status: 'success',
    input: {
      message: {
        id: '66d86484-dad5-4b5e-b80e-dea38c1537c4',
      },
      structured_load_data: {
        external_id: '66cc3651-6bcc-4521-a75e-beb0b76d10a3',
      },
      documents: [
        {
          external_id: '66cc3651-6bcc-4521-a75e-beb0b76d10a3',
          document_ref:
            'https://lm-dev-loads-emails.s3.us-east-1.amazonaws.com/attachments/eo25f0la4go49vsall22lrlqr0spbmmnv25hi9o1_BOBTAIL_5588625_f3c24f73-2c21-4152-86c5-b2ae0bf47e45_cdpc4BTg4f.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAVYRXZV7PYTMRNIM6%2F20240717%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240717T125859Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjECUaCXVzLWVhc3QtMSJGMEQCIAw1LmOv%2BqbkbHTnVk4uRrbXsqj0UIOyMpMTtPb3ONMyAiA92r9topLHE%2F24lda8MU58qzBovJM0ptlQdS0n7SU%2FpiqYAwju%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAIaDDM5NjMyNzc1OTgzOSIM7PLlLclGiHAsey7iKuwCXCAErjSy9C%2FIEcJP35B%2FvGR7mzOVG5tZ62NZo2r%2BGPNFVhFP32nV67OYSXQk6e7IsHX0bEg5EjtorKkxkyL7IkBSzEXSMLKvpC8ChfkyupAV4Mpi7s8GKVvIcsKQtV%2F0eAjyzf%2BNOpoeDIt%2BT6pJgwzAWev4pOVdKJWBXBIcJ5l%2By6u3Ybzv3lTtSV0V9hXBYidkYfuJ4UCPXgYlx4ftQqt2uZsz2xoujlNIe5np%2BjBXziIvbuJ%2BzmxbaAIbhm%2FXqy5PSIgGMXvf29P3BWkLNYBimR%2FI7ckQXcfsm4wM7TQk%2FUeHA6QKR1bSUbCZRmlLy2fO92gN2i6z2NClRGGD1Bmgc5o8I%2Fqv0OUkpDFVn%2FNfFhJvoyM41uh1BbdW10r%2B%2FVpDqy8Oi9xvo%2BaIH9X4mXdd%2FUq9aDbfCQ3zYUtFCtDB1F7%2BiF%2F5%2BSQJf8picPCUWC6jk2r2Iuc4uyUmeyeXHWV7rUHe%2B1NuZ7Dn3DCTgN%2B0BjqnAWxJWYvShvooUabfPamaemIbw4wTvsqJucDC98DyRz5AEwhw29GNdzzmkbd2qEQJJNVBiddmMhdB8CiYZUr%2Fk65pv2pn3C2xLtjG5tGQaaGEUZ7OxQESYfriD0BWwSXh%2FXoNsUD%2FChYpR9J31H9mM4SAdFOoDlnW32DwbSlXwAHeMOX1JPgxCd%2FqgFeTPiIOL%2FWAQjt%2FFyCVO6vkrhq2wprv0FfvtEDx&X-Amz-Signature=8b2eed1dcaf3bd2057730d2d447a6c8682b65020e0171b5d340f61461ecdeebd&X-Amz-SignedHeaders=host&x-id=GetObject',
        },
      ],
    },
    result: {
      verify_load_response: {
        BOL_vs_rate_confirmation_probability: 0.0,
        structured_load_data_vs_rate_confirmation_probability: 0.0,
        carrier_invoice_vs_rate_confirmation_probability: 0.0,
        checks: {
          damages_or_shortages_probability: null,
          produce_probability: 0.44058947058767617,
          multistop_probability: 0.37777777777777777,
          signature_present_probability: null,
          late_delivery_probability: 0.0,
          bol_pages_missing_probability: 0.0,
          receiver_stamp_present: false,
          is_tonu: false,
        },
        potential_duplicate_loads: [
          '66a774f5-6b57-4fa1-9fce-e4f3e134a57f',
          '66a774f5-b3e9-4c14-82b9-d139cb001fa7',
          '66a744d8-28d2-4649-90d5-76f63cefe86f',
          '66a74595-cf98-4a36-a0e3-eed840ec3602',
          '66a744d9-33df-43ed-9234-aaeb5e8d44aa',
          '66a774f5-396d-4588-8b2f-28c38bca1f28',
          '66a774f5-6433-423d-bc76-60fb7ce52e98',
        ],
        funding_methods: [],
        fields: {
          delivery_address: {
            rate_confirmation_vs_BOL_match_probability: null,
            rate_confirmation_parsed: {
              receiver_address_address_type: 'Street Address',
              receiver_address_street: '146 Roberts Street',
              receiver_address_city: 'Asheville',
              receiver_address_zip: '28801',
              receiver_address_state: 'North Carolina',
            },
            structured_load_data_vs_BOL_distance_in_miles: null,
            structured_load_data_vs_rate_confirmation_distance_in_miles: null,
            BOL_vs_structured_load_data_match_probability: null,
            BOL_parsed: {
              receiver_address_address_type: null,
              receiver_address_street: null,
              receiver_address_city: null,
              receiver_address_zip: null,
              receiver_address_state: null,
            },
            rate_confirmation_vs_BOL_distance_in_miles: null,
            structured_load_data: null,
            BOL: '',
            rate_confirmation:
              '146 Roberts Street, Asheville, North Carolina 28801, United States',
            rate_confirmation_vs_structured_load_data_match_probability: null,
          },
          broker_address: {
            rate_confirmation:
              'North Little Rock, Arkansas 72115, United States',
            rate_confirmation_parsed: {
              broker_address_address_type: 'Ambiguous',
              broker_address_street: null,
              broker_address_city: 'North Little Rock',
              broker_address_zip: '72115',
              broker_address_state: 'Arkansas',
            },
            BOL: '',
            BOL_parsed: {
              broker_address_address_type: null,
              broker_address_street: null,
              broker_address_city: null,
              broker_address_zip: null,
              broker_address_state: null,
            },
            match_probability: null,
          },
          delivery_date: {
            BOL: null,
            rate_confirmation: '2024-05-02',
            delta_in_days: null,
            match_probability: null,
          },
          remit_to_address: {
            carrier_invoice: null,
          },
          equipment: {
            rate_confirmation: 'Dry Van,',
            BOL: '',
            match_probability: null,
          },
          invoice_number: {
            carrier_invoice: null,
          },
          tonu: {
            carrier_invoice: false,
            rate_confirmation: false,
          },
          commodity: {
            rate_confirmation: 'TRIUMPH FLOOR LOADED CABINETS',
            BOL: '',
            match_probability: 0.0,
          },
          carrier_name: {
            rate_confirmation_vs_BOL_match_probability: null,
            carrier_invoice_vs_structured_load_data_match_probability: null,
            BOL_vs_structured_load_data_match_probability: null,
            rate_confirmation_canonical: ['LRS CONTRACTING INC'],
            rate_confirmation_raw_all: ['SIRIUS LOGISTICS LLC (1104009)'],
            carrier_invoice_vs_BOL_match_probability: null,
            rate_confirmation_recent_preference: [],
            rate_confirmation_raw: 'SIRIUS LOGISTICS LLC (1104009)',
            carrier_invoice_vs_rate_confirmation_match_probability: null,
            carrier_invoice: null,
            structured_load_data: null,
            BOL: null,
            rate_confirmation: 'SIRIUS LOGISTICS LLC (1104009)',
            rate_confirmation_vs_structured_load_data_match_probability: null,
          },
          BOL_pages: {
            present: 0,
            expected: [],
            missing: [],
          },
          pickup_date: {
            BOL: null,
            rate_confirmation: '2024-05-01',
            delta_in_days: null,
            match_probability: null,
          },
          rate: {
            rate_confirmation_lumper_rate: null,
            carrier_invoice_vs_structured_load_data_match_probability: null,
            rate_confirmation_other_accessorial_charges: null,
            rate_confirmation_total_rate: 1170.0,
            rate_confirmation_line_haul_rate: 1170.0,
            carrier_invoice_vs_rate_confirmation_match_probability: null,
            rate_confirmation_fuel_surcharge: null,
            structured_load_data: null,
            carrier_invoice_total_rate: null,
            rate_confirmation_vs_structured_load_data_match_probability: null,
          },
          broker_email_domains: {
            rate_confirmation: ['priority1.com', 'priority1.com'],
            rate_confirmation_vs_known_broker_domain_probability: null,
          },
          carrier_mc: {
            rate_confirmation: null,
            BOL: null,
            structured_load_data: null,
            rate_confirmation_vs_BOL_match_probability: null,
            BOL_vs_structured_load_data_match_probability: null,
            rate_confirmation_vs_structured_load_data_match_probability: null,
          },
          broker_name: {
            rate_confirmation_vs_BOL_match_probability: null,
            carrier_invoice_vs_structured_load_data_match_probability: null,
            BOL_vs_structured_load_data_match_probability: null,
            rate_confirmation_canonical: ['PRIORITY-1 INC'],
            rate_confirmation_raw_all: ['Priority 1 Inc.'],
            carrier_invoice_vs_BOL_match_probability: null,
            rate_confirmation_recent_preference: [],
            rate_confirmation_raw: 'Priority 1 Inc.',
            carrier_invoice_vs_rate_confirmation_match_probability: null,
            carrier_invoice: null,
            structured_load_data: null,
            BOL: null,
            rate_confirmation: 'Priority 1 Inc.',
            rate_confirmation_vs_structured_load_data_match_probability: null,
          },
          carrier_root_canonical_entity_id: {
            rate_confirmation: '1583bad5-a502-5fbf-8e30-d15ce6930a67',
          },
          pickup_address: {
            rate_confirmation_vs_BOL_match_probability: null,
            rate_confirmation_parsed: {
              shipper_address_address_type: 'Street Address',
              shipper_address_street: '590 Principio Parkway West',
              shipper_address_city: 'North East',
              shipper_address_zip: '21901',
              shipper_address_state: 'Maryland',
            },
            structured_load_data_vs_BOL_distance_in_miles: null,
            structured_load_data_vs_rate_confirmation_distance_in_miles: null,
            BOL_vs_structured_load_data_match_probability: null,
            BOL_parsed: {
              shipper_address_address_type: null,
              shipper_address_street: null,
              shipper_address_city: null,
              shipper_address_zip: null,
              shipper_address_state: null,
            },
            rate_confirmation_vs_BOL_distance_in_miles: null,
            structured_load_data: null,
            BOL: '',
            rate_confirmation:
              '590 Principio Parkway West, North East, Maryland 21901, United States',
            rate_confirmation_vs_structured_load_data_match_probability: null,
          },
          broker_root_canonical_entity_id: {
            rate_confirmation: '0cdadee1-7018-567a-8d83-b86bfeb81601',
          },
          po_reference_number: {
            BOL_reference_number_conformity: null,
            rate_confirmation_vs_BOL_match_probability: null,
            carrier_invoice_reference_number_conformity: null,
            po_reference_number_recent_broker_sequence: [
              '60108415000',
              '60108437145',
              '60108386321',
              '60108424519',
              '60108423304',
              '60108317267',
              '60108430236',
            ],
            carrier_invoice_vs_structured_load_data_match_probability: null,
            rate_confirmation_reference_number_conformity: null,
            BOL_vs_structured_load_data_match_probability: null,
            rate_confirmation_raw_all: ['60107435743'],
            carrier_invoice_vs_BOL_match_probability: null,
            rate_confirmation_raw: '60107435743',
            carrier_invoice_vs_rate_confirmation_match_probability: null,
            carrier_invoice: null,
            structured_load_data: null,
            BOL: null,
            rate_confirmation: '60107435743',
            rate_confirmation_vs_structured_load_data_match_probability: null,
          },
          carrier_dot: {
            rate_confirmation: null,
            BOL: null,
            structured_load_data: null,
            rate_confirmation_vs_BOL_match_probability: null,
            BOL_vs_structured_load_data_match_probability: null,
            rate_confirmation_vs_structured_load_data_match_probability: null,
          },
          shipper_reference_number: {
            rate_confirmation_vs_BOL_match_probability: null,
            carrier_invoice_vs_structured_load_data_match_probability: null,
            BOL_vs_structured_load_data_match_probability: null,
            carrier_invoice_vs_BOL_match_probability: null,
            carrier_invoice_vs_rate_confirmation_match_probability: null,
            carrier_invoice: null,
            structured_load_data: null,
            BOL: null,
            rate_confirmation: null,
            rate_confirmation_vs_structured_load_data_match_probability: null,
          },
          temperature: {
            rate_confirmation: '',
            BOL: '',
            match_probability: 1.0,
          },
          broker_email: {
            rate_confirmation: 'trey.hobson@priority1.com;tlap@priority1.com',
            BOL: '',
            structured_load_data: null,
            rate_confirmation_vs_BOL_match_probability: null,
            BOL_vs_structured_load_data_match_probability: null,
            rate_confirmation_vs_structured_load_data_match_probability: null,
          },
          total_product_weight: {
            rate_confirmation: '35000.00 lb',
            BOL: null,
            match_probability: null,
          },
          remit_to_name: {
            carrier_invoice: null,
          },
          broker_reference_number: {
            BOL_reference_number_conformity: null,
            rate_confirmation_vs_BOL_match_probability: null,
            carrier_invoice_reference_number_conformity: null,
            po_reference_number_recent_broker_sequence: [
              '60108415000',
              '60108437145',
              '60108386321',
              '60108424519',
              '60108423304',
              '60108317267',
              '60108430236',
            ],
            carrier_invoice_vs_structured_load_data_match_probability: null,
            rate_confirmation_reference_number_conformity: null,
            BOL_vs_structured_load_data_match_probability: null,
            rate_confirmation_raw_all: ['60107435743'],
            carrier_invoice_vs_BOL_match_probability: null,
            rate_confirmation_raw: '60107435743',
            carrier_invoice_vs_rate_confirmation_match_probability: null,
            carrier_invoice: null,
            structured_load_data: null,
            BOL: null,
            rate_confirmation: '60107435743',
            rate_confirmation_vs_structured_load_data_match_probability: null,
          },
        },
      },
      status: 'success',
      message: 'Missing BOL document.',
      debtor_system_verification: {
        message: 'failure',
        error: "broker 'Priority 1 Inc.' not recognized",
      },
    },
    message: 'Missing BOL document.',
    load_id: '66d849bf-f663-4a21-abd3-9870be560064',
    document_ids: ['c2ea59ab-f306-4963-85f6-97511551a046'],
  };
  const model = plainToInstance(PeruseCreateLoadJobResult, plain);
  Object.assign(model, data);
  return model;
};

export const buildStubPeruseLoadResponse = (
  data?: Partial<PeruseLoadResponse>,
): PeruseLoadResponse => {
  const plain = {
    entity_type: 'load',
    entity_data: {
      BOL_vs_rate_confirmation_probability: 0.0,
      potential_duplicate_loads: [
        '66a774f5-6b57-4fa1-9fce-e4f3e134a57f',
        '66a774f5-b3e9-4c14-82b9-d139cb001fa7',
        '66a744d8-28d2-4649-90d5-76f63cefe86f',
        '66a74595-cf98-4a36-a0e3-eed840ec3602',
        '66a744d9-33df-43ed-9234-aaeb5e8d44aa',
        '66a774f5-396d-4588-8b2f-28c38bca1f28',
        '66a774f5-6433-423d-bc76-60fb7ce52e98',
      ],
      factorsoft_note_xml_url: null,
      fields: {
        delivery_address:
          '146 Roberts Street, Asheville, North Carolina 28801, United States',
        broker_address: 'North Little Rock, Arkansas 72115, United States',
        delivery_date: '2024-05-02',
        remit_to_address: null,
        equipment: 'Dry Van,',
        invoice_number: null,
        tonu: false,
        commodity: 'TRIUMPH FLOOR LOADED CABINETS',
        carrier_name: 'SIRIUS LOGISTICS LLC (1104009)',
        BOL_pages: null,
        pickup_date: '2024-05-01',
        rate: 1170.0,
        broker_email_domains: ['priority1.com', 'priority1.com'],
        load_number: '60107435743',
        carrier_mc: null,
        broker_name: 'Priority 1 Inc.',
        carrier_root_canonical_entity_id:
          '1583bad5-a502-5fbf-8e30-d15ce6930a67',
        pickup_address:
          '590 Principio Parkway West, North East, Maryland 21901, United States',
        broker_root_canonical_entity_id: '0cdadee1-7018-567a-8d83-b86bfeb81601',
        carrier_dot: null,
        shipper_reference_number: null,
        temperature: '',
        broker_email: 'trey.hobson@priority1.com;tlap@priority1.com',
        total_product_weight: '35000.00 lb',
        remit_to_name: null,
        broker_reference_number: '60107435743',
      },
      checks: {
        damages_or_shortages_probability: null,
        produce_probability: 0.44058947058767617,
        multistop_probability: 0.37777777777777777,
        signature_present_probability: null,
        late_delivery_probability: 0.0,
        bol_pages_missing_probability: 0.0,
        receiver_stamp_present: false,
        is_tonu: false,
      },
      structured_load_data_vs_rate_confirmation_probability: 0.0,
      carrier_invoice_vs_rate_confirmation_probability: 0.0,
      factorsoft_xml_url: null,
      funding_methods: [],
    },
    note: 'Structured Data vs Rate Confirmation match\nBOL present',
    status: 'pending',
    document_ids: [
      '5188393b-8fdf-44ce-8e5b-f8be887b19ed',
      'c2ea59ab-f306-4963-85f6-97511551a046',
      '2b9e5a6f-02b6-4225-804d-390cea38e762',
    ],
    task_id: '66d849cd-6497-4218-9f3f-9fb6496058a1',
    document_urls: [],
    audit_log: [
      {
        user: 'dev+bobtail@peruse.ml',
        operation: 'create',
        changed_at: '2024-09-04T11:51:29.086Z',
      },
      {
        user: null,
        operation: 'update',
        changed_at: '2024-09-04T11:51:42.439Z',
      },
      {
        user: 'dev+bobtail@peruse.ml',
        operation: 'update',
        changed_at: '2024-09-04T13:09:03.420Z',
      },
      {
        user: 'dev+bobtail@peruse.ml',
        operation: 'update',
        changed_at: '2024-09-04T13:45:40.021Z',
      },
    ],
    load_path:
      '/files/loads?activeTaskId="66d849cd-6497-4218-9f3f-9fb6496058a1"',
    entity_id: '66d849bf-f663-4a21-abd3-9870be560064',
    job_id: '66d86482-2416-4c7b-98b6-b58ded700347',
  };
  const model = plainToInstance(PeruseLoadResponse, plain);
  Object.assign(model, data);
  return model;
};
